- integration_tests/data/expected/expected_sample_data_z_score.csv
- macros/metrics/base/build_in/column_default.sql
When defining configuration for `not_match_regex` metric, it is done in this way:
```
not_match_regex:
regex: [A-Z]+
```
The previous implementation takes in `[A-Z]+` as the pattern that defines what values don't match in the column, so it counts the values that match the pattern while the proposed change will count the number of values that don't match the given regex `[A-Z]+`. My thinking is that most users know the pattern they are trying to match and will like to consider others as non-matching. 
Subtract the row count from the total matching the given regex.
> use not_match_regex in context of regex given

- integration_tests/data/public_macros/normalizing/us_states_normalization.csv
- integration_tests/models/public_macros/normalizing/us_states_normalized.sql
- macros/public/normalizing/normalize_values.sql
Previously, we use incorrect and correct as column names expected for the `normalize_values` macro. I feel renaming to source and target is more semantically correct.
> use source and target as column names for normalizing

- integration_tests/data/expected/expected_duplicates.csv
- integration_tests/models/public_macros/filtering/duplicates.sql
- integration_tests/models/public_macros/filtering/schema.yml
- integration_tests/python_tests/test_filters.py
- macros/public/filtering/get_duplicates.sql
- macros/public/filtering/remove_duplicates.sql
- macros/utils/comma_delimited_list.sql
- macros/utils/deduplication/add_duplication_context.sql
new macro filter_get_duplicates
the issue is described in
https://github.com/re-data/re-data/issues/143
new macro accepts the same arguments as 
[filter_remove_duplicates macro](https://re-data.github.io/re-data/latest/docs/reference/data_preparation/data_filtering#filter_remove_duplicates)
but returns all the rows which have been filtered away by filter_remove_duplicates.
macro adds 2 new duplication context columns to the table:
- re_data_duplicates_group_rows_count
number of duplicate rows with the same key columns values as for the current row
- re_data_duplicates_group_row_number
number of current row within the group of duplicate rows with the same key columns values as for the current row
> Feature macro filter_get_duplicates

- macros/utils/json/quote.sql
When quoting large strings, escaped characters are not preserved. Using raw strings instead can help preserve such characters.
[Reference](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical)
> use raw strings for bigquery when quoting strings with escaped characters

- .github/workflows/run-db-tests.yml
- integration_tests/macros/drop_all_schemas.sql
Dropping schemas with [adapter.drop_schema](https://docs.getdbt.com/reference/dbt-jinja-functions/adapter#drop_schema) doesn't seem to work with redshift. Pending when we can identify and resolve the cause, we fall back to using DDL statements to drop schemas in redshift.
> use ddl commands to drop schema for redshift

- .github/workflows/run-db-tests.yml
When a release is created, the event ref is contains a tag number e.g. `0.6.0`. We currently only replace `-` with `_`. Generating a schema name like `dq_0.6.0` is invalid. Ideally we should have something like `dq_0_6_0`
This change replaces all non alphanumeric characters with `_` ensuring the dynamically generated schema name is always vaild.
> replace non alphanumeric chars with underscore

- .github/workflows/generate-docs.yml
- .github/workflows/run-db-tests.yml
- integration_tests/requirements.txt
https://github.com/pallets/markupsafe/issues/284 introduced a change that breaks installation process in our integration tests.
dbt has fixed this in `dbt-core` so we ensure that the integration tests use the latest version.
> update dbt-core version used in testing

- models/anomalies/re_data_schema_changes.sql
- models/anomalies/re_data_z_score.sql
- models/logs/re_data_test_history.sql
- models/metrics/types/base/re_data_base_metrics.sql
- models/metrics/types/schema/re_data_columns_over_time.sql
- packages.yml
We added some columns to the `re_data_z_score.sql` model and would like to handle running on past schemas that don't contain new columns. By default dbt will ignore the new columns but that's not what should happen in our case.
[Reference](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-if-the-columns-of-my-incremental-model-change)
> handle schema change for re_data_z_score model

- models/anomalies/re_data_schema_changes.sql
When a model has its config property `re_data_monitored` changed to true from false or vice versa, re_data currently detects columns in affected models as either all removed or added respectively. This is an unexpected behaviour as monitoring or un-monitoring a node doesn't constitute schema changes.
Ensure that schema changes are only detected for currently monitored tables.
Note that in future releases, we may consider adding a message that shows a table just started being monitored and vice versa.
> fix bug in schema changes

- macros/meta/get_monitored.sql
- macros/post_hook/re_data_monitored.sql
- macros/public/store/export_alerts.sql
- macros/utils/is_list.sql
- macros/utils/mock/empty_tables.sql
This feature allows the user to set slack owners for a particular model and also configuring the member id mapping so slack users can be mentioned using the notifications feature.
Usage:
Model
```sql
{{
config(
re_data_monitored=true,
re_data_time_filter='time_created',
re_data_anomaly_detector={'name': 'z_score', 'threshold': 2.2},
re_data_slack_owners=['backend'], # this can either be set to a particular user or a team defined in `re_data:slack_config`
)
}}
```
dbt_project.yml
```yaml
vars:
re_data:anomaly_detector:
name: modified_z_score
threshold: 3
re_data:slack_config:
deji: U02FHBSTXXX
mateusz: U01F80NJXXX
emmanuel: U02RD3S3XXX
backend: [deji, mateusz] # defining a team, this consists of keys within the same yaml dictionary
frontend: [deji, emmanuel]
```
When a slack notification …
> configure slack alerting per model to specific users

- macros/meta/get_monitored.sql
When somebody is using an alias in the dbt model config, dbt creates a table with the alias name used.
We need to take this into account when computing metrics.
> Fix problem with alias not properly handled

- macros/metrics/base/queries.sql
- macros/public/store/export_table_samples.sql
- macros/public/store/export_tests_history.sql
- macros/public/store/generate_overview.sql
- macros/run_end/save_results_history.sql
- macros/samples/internal_model_template.sql
- macros/utils/agate/row_value.sql
- macros/utils/mock/empty_tables.sql
- models/internal/samples/re_data_last_table_samples.sql
- models/internal/samples/re_data_last_table_samples_part.sql
- models/metrics/types/samples/re_data_table_samples.sql
- Constructs json from the results of `run_query()` using jinja2.
- Export tests history to a separate file
- Create model that stores sample rows for monitored tables
> serialize tables exported to json 

- macros/utils/agate/row_value.sql
When serializing to json with jinja, we realized that the value could contain a json object formatted with newlines, so we need to escape those newlines to ensure validity of the final json.
Escape newline special character (`\n`) in `agate_to_list` macro
> escape newline characters in json values

- macros/meta/information_schema.sql
Currently it cannot load any columns info for Redshift external tables. It fails badly even during `dbt compile`.
Use the default query inside `call statement('columns')`, but also union it with info from pg_catalog.svv_columns where the info about external tables and late binding views can be found.
Inspired by [implementation in dbt.](https://github.com/dbt-labs/dbt-redshift/blob/fe91015ac6361c48531b439ac72d3f477d9cc07b/dbt/include/redshift/macros/adapters.sql).
> support external tables and late binding views

- macros/db/postgres/postgres_type_db.sql
- macros/utils/json/to_single_json.sql
- models/metrics/for_anomalies/re_data_last_stats.sql
- Fixing #100
- `to_single_json.sql` file formatting
Fixed related Jinja SQL templates
> Adding ability to install re_data for Greenplum database

- macros/utils/fivetran_utils/json_extract.sql
- macros/utils/fivetran_utils/percentile.sql
add `re_data` namespace to fivetran-utils macro in `macros/utils/fivetran_utils`
> add namespace to fivetran_utils macros, fix #103

- macros/db/bigquery/quote_string.sql
* Fixes https://github.com/re-data/re-data/issues/370
* Reference to google big query docs: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#string_and_bytes_literals
Using raw strings fixes the `dbt test` command on-run-end failures because all strings are now raw strings meaning backslash characters do not act as escape sequences
> use raw string in google bigquery to avoid parsing illegal escape characters

- .github/workflows/generate-docs.yml
- .github/workflows/run-db-tests.yml
- .gitignore
- dbt_project.yml
- integration_tests/packages.yml
- integration_tests/requirements.txt
- macros/public/store/generate_overview.sql
- packages.yml
- profiles.yml
- Now has compatibility for dbt-core 1.7 and for dbt_utils 1.1
- Updated dbt versions to 1.7 and dbt_utils version to 1.1 in GitHub Actions files and config files and re-ran tests
- Fixed BigQuery connection issues by using `method: service-account-json` in the profiles.yml file
- Fixed path issue in the `generate_overview` macro that occurs when moving between dbt-core 1.4 and 1.5
> Update to dbt-core 1.7 compatibility

- .github/workflows/generate-docs.yml
- .github/workflows/run-db-tests.yml
- Makefile
- README.md
- integration_tests/.gitignore
- CI should runner smoother now with less unnecessary runs
- Local development should be easier now
- Jobs that run commands on data warehouses that aren't Postgres now only run when a PR is merged to the `main` branch
- Makefile runs all most CLI commands for development and uses [act](https://github.com/nektos/act) to run the GitHub Actions files locally
> Makefile and CI upgrades

- macros/run_end/save_results_history.sql
Fixes Issue : https://github.com/re-data/re-data/issues/397 (save_test_history macro doesn't store compiled_sql after dbt-core>=v1.3.0)
By using the `node.compiled_sql` and `node.compiled_code` in an `or` condition so that the logic works with both `dbt-core<v1.3.0` and `dbt-core>=v1.3.0`.
> Use node.compiled_code for dbt-core>=v1.3.0

- dbt_project.yml
- models/alerts/re_data_alerts.sql
closes https://github.com/re-data/re-data/issues/403
Add a var for `re_data_anomalies_filtered` that can override the alerts. In this way, you can select from `re_data_anomalies` what anomalies you would like to show in alerts in the UI, and also notify in slack.
After this change, the user can create a model (view, ephemeral, table, anything works) on top of `re_data_anomalies`, for example, the view `anomaly_filters`
```
SELECT
*
FROM
{{ ref('re_data_anomalies') }}
WHERE
table_name LIKE '%my_test_table%'
AND column_name = 'age'
AND metric = 'avg'
```
Then set up re_data:re_data_anomalies_filtered: anomaly_filters` in `dbt.project.yml` and that is all.
------------
Tried it on my current project by loading
```
packages:  
- git: https://github.com/suelai/dbt-re-data.git
revision: …
```
> add re_data_anomalies_filtered as var

- macros/metrics/base/build_in/column_default.sql
- macros/utils/column_types.sql
*Describe what the change is solving*
*It helps to add screenshots if it affects the frontend.*
Get counts of `TRUE` and `FALSE` for boolean values. Right now the column type are text and numeric only
change the macros that detect the column types for BigQuery to recognise booleans and add two metrics of `count_true` and `count_false`
*Describe the solution*
Add an if condition to `bigquery__get_column_type` to include the `boolean` column type. Add two metrics of count_true` and `count_false`
relates to https://github.com/re-data/re-data/issues/405
> add boolean and boolean metrics

- dbt_project.yml
- models/alerts/re_data_alerts.sql
Allows test warnings to be surfaced in the alerts model so that the alerts page in the re_data UI can list warnings as well as failures
Adds a new variable `re_data:show_warns_as_alerts` (defaults to false) that when set to true will modify the SQL in the alerts model to select tests with the warn status
> Feat: warns as alerts
